[unstable]
## This is so that memory related functions are available to us
build-std-features = ["compiler-builtins-mem"]
## This is because we are using a custom target and the core library is not net compiled for this target
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-juno.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
